name: Python CI

on:
  push:
    branches:
      - lab-03
  pull_request:
    branches:
      - lab-03

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt

    # Run Linter
    - name: Lint code
      run: |
        pip install flake8
        flake8 app_python

    # Run Unit Tests
    - name: Run tests
      run: python -m unittest discover -s app_python -p "test_*.py"

  docker-steps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker image
      run: docker build -t niksgont/moscow-time-app .

    # Push Docker image
    - name: Push Docker image
      run: docker push niksgont/moscow-time-app
