name: Python CI

on:
  push:
    branches:
      - lab-03
  pull_request:
    branches:
      - lab-03

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt

    # Run Linter
    - name: Lint code
      run: |
        pip install flake8
        flake8 app_python

    # Run Unit Tests
    - name: Run tests
      run: python -m unittest discover -s app_python -p "test_*.py"

    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: app_python
        file: app_python/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-python:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-python:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app-python:buildcache,mode=max